---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[openssh]
      - recipe[openssh::iptables]
      - recipe[iptables-logging-cookbook::default]
    attributes:
      iptables:
        logging:
          enabled: true

